In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
# code to check if GPU available or not
if torch.cuda.is_available():
    print("GPU available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}") # will display what gpu we are uing
else:
    print("GPU not available. Using CPU.")

GPU available
Using GPU: Tesla T4


## Creating a Tensor


In [3]:
# using empty
torch.empty(2,3)

''' empty function - allocates memory for us
ex: let's say we mentioned we want (2,3) so empty function will
go create this much(this size) space in memory but does not assign
any value to the space, already the value which exists in mem(garbage value)
 it shows as it is, no new value is assigned '''

tensor([[-4.3517e-10,  4.5440e-41, -5.8148e+13],
        [ 3.2589e-41, -6.1527e+01,  4.5439e-41]])

In [4]:
# check type
a = torch.empty(2,3)
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

''' zero function - creates a tensor for us with our mentioned size
and initialises all its values with zeros '''

''' let's say we are building a NN and we want to create biases for
different neurons and we want that initially biases values are zero
so this is a very good way to initialise those biases '''

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

''' ones function - creates a tensor for us with our mentioned size
and initialises all its values with ones '''

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

''' rand function - creates a tensor for us with our mentioned size
and initialises all its values with random values b/w 0 and 1 '''

''' weight initialisation technique where we start with random values
so this is a very good way to create that particular matrix '''

tensor([[0.5870, 0.1248, 0.9186],
        [0.6836, 0.8308, 0.0472]])

In [9]:
# use of seed
torch.rand(2,3)
# if we run rand again then the values of the tensor will change
# if we want our value to not change everytime we rerun the rand func
# we can define seed.

tensor([[0.9036, 0.0019, 0.9347],
        [0.9423, 0.3198, 0.8922]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

''' Using tensor func we can create manual tensors '''

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways of creating tensor

# arange - we provide range and step/jump
print("using arange ->", torch.arange(0,10,2))

# using linspace - linearly spaced, ex: (0,10,10) - range is 0 to 10 we want 10 evenly spaced values
print("using linspace ->", torch.linspace(0,10,10))

# using eye - eye for identity matrix - ex: torch.eye(5) - we want 5x5 identity matrix
# identity matrix - diagonal elements are 1 all else 0
print("using eye ->", torch.eye(5))

# using full - specifies shape ex: (3,3) and what every element must be ex: 5
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [ ]:
# let's say we have a tensor and we want to build another tensor of that shape
# if that's our requirement then we have some methods for it
# they are :

In [16]:
# using empty func we want to build another tensor of the same shape
torch.empty_like(x) # (_) mention which tensor's shape we want to copy

tensor([[139271844049280, 139271839667136, 139271844912880],
        [             97,  99887361943504, 139275856198960]])

In [17]:
# similarly we have another method

torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x)
''' this will not work
because we are saying we want a new tensor like 'x' with 'values randomly intialised(rand func)'
but our in tensor 'x' all its elements/items are 'integers'
whereas rand func will generate 'floats b/w 0 and 1'
that is why this code doesn't work
therefore here we have to explicitly say that we want to generate float type values '''

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
# before solving this problem
# let's first learn about datatypes

In [28]:
# (learn about data types below and then come to this cell)
# this fixes the above problem
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [21]:
# find data type
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.dtype

torch.int64

In [23]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to() - to change the data type of already made tensor(existing tensor)

In [25]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#data types available in PyTorch

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations on Tensor

### 1. Scalar operation

In [29]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [30]:
# addition
print(x + 2)
# substraction
print(x - 2)
# multiplication
print(x * 3)
# division
print(x / 3)
# int division
print((x * 100)//3)
# mod
print(((x * 100)//3)%2)
# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element Wise Operations

In [31]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [32]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [33]:
# sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [34]:
#multiply

a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [35]:
# division

a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [36]:
# power

a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [37]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [38]:
c = torch.tensor([1,-2,3,-4])

In [39]:
# abs - absolute value of tensor

torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [41]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [42]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
# clamp - we can keep the numbers in a particular range
torch.clamp(d, min = 2, max = 3)
# ex if we define a range of min = 2 and max = 3
# then the numbers smaller than will become 2
# and the numbers greater than 3 will become 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation

In [ ]:
# reduction operation - reducing a whole tensor to a single number

In [8]:
 e = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
 e

tensor([[6., 7., 0.],
        [5., 3., 7.]])

In [9]:
# sum
print(torch.sum(e))

#sum along column
print(torch.sum(e, dim = 0))

#sum along row
print(torch.sum(e, dim = 1))

tensor(28.)
tensor([11., 10.,  7.])
tensor([13., 15.])


In [10]:
# mean
print(torch.mean(e))

# mean along column
print(torch.mean(e, dim = 0))

# mean along row
print(torch.mean(e, dim = 1))

tensor(4.6667)
tensor([5.5000, 5.0000, 3.5000])
tensor([4.3333, 5.0000])


In [11]:
# median
torch.median(e)

tensor(5.)

In [12]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(7.)
tensor(0.)


In [13]:
# product
torch.prod(e)

tensor(0.)

In [14]:
# standard deviation
torch.std(e)

tensor(2.7325)

In [15]:
# variance
torch.var(e)

tensor(7.4667)

In [16]:
# argmax - tells us the position of the largest element/item.
torch.argmax(e)

tensor(1)

In [17]:
# argmin - tells us the position of the smalles element/item.
torch.argmin(e)

tensor(2)

### 4. Matrix Operations

In [18]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 3, 7],
        [3, 2, 8]])
tensor([[6, 1],
        [5, 6],
        [7, 6]])


In [19]:
# matrix multiplication

torch.matmul(f,g)

tensor([[76, 62],
        [84, 63]])

In [20]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [21]:
f

tensor([[2, 3, 7],
        [3, 2, 8]])

In [22]:
#transpose - torch.transpose(matrix_name, the dim you want to swap, the dim you want to swap it with)
torch.transpose(f,0,1)

tensor([[2, 3],
        [3, 2],
        [7, 8]])

In [23]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 7., 3.],
        [3., 9., 2.],
        [4., 4., 7.]])

In [24]:
# determinant
torch.det(h)

tensor(222.)

In [25]:
# inverse
torch.inverse(h)

tensor([[ 0.2477, -0.1667, -0.0586],
        [-0.0586,  0.1667, -0.0225],
        [-0.1081,  0.0000,  0.1892]])

### 5. Comparison Operations

In [27]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)

print(i)
print(j)

tensor([[5, 1, 8],
        [7, 3, 4]])
tensor([[2, 9, 7],
        [3, 8, 3]])


In [29]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i >= j)
# less than equal to
print(i <= j)

tensor([[ True, False,  True],
        [ True, False,  True]])
tensor([[False,  True, False],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True, False,  True],
        [ True, False,  True]])
tensor([[False,  True, False],
        [False,  True, False]])


### 6. Special Functions

In [30]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[6., 5., 2.],
        [2., 9., 7.]])

In [31]:
# log
torch.log(k)

tensor([[1.7918, 1.6094, 0.6931],
        [0.6931, 2.1972, 1.9459]])

In [32]:
# exponent
torch.exp(k)

tensor([[4.0343e+02, 1.4841e+02, 7.3891e+00],
        [7.3891e+00, 8.1031e+03, 1.0966e+03]])

In [33]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.2361, 1.4142],
        [1.4142, 3.0000, 2.6458]])

In [34]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9933, 0.8808],
        [0.8808, 0.9999, 0.9991]])

In [35]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.0180, 0.0067],
        [0.0180, 0.9820, 0.9933]])

In [36]:
# relu
torch.relu(k)

tensor([[6., 5., 2.],
        [2., 9., 7.]])

### Inplace Operation

In [37]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2713, 0.8973, 0.0226],
        [0.6265, 0.8295, 0.4959]])
tensor([[0.6671, 0.9162, 0.1407],
        [0.6156, 0.3601, 0.7854]])


In [ ]:
''' let's say we are performing any operations on these tensors
for example: let's say addition operation (m + n),
so element wise operations are performed and the result is stored
in a new tensor (new tensor in memory)
will occupy some space in memory
this is problematic in some scenarios
ex: we are working on a very large dataset represented as a tensor
and we are applying tensor operation on it so the same large size
new tensor will be formed , so it will eat up a lot of space in memory
which is not desirable
therefore we try to make changes inplace '''

In [38]:
# adding m + n and storing it in m

m.add_(n)

tensor([[0.9383, 1.8135, 0.1632],
        [1.2421, 1.1895, 1.2812]])

In [39]:
m


tensor([[0.9383, 1.8135, 0.1632],
        [1.2421, 1.1895, 1.2812]])

In [40]:
torch.relu(m) # new tensor is created for result

tensor([[0.9383, 1.8135, 0.1632],
        [1.2421, 1.1895, 1.2812]])

In [41]:
m.relu_() # inplace operation

tensor([[0.9383, 1.8135, 0.1632],
        [1.2421, 1.1895, 1.2812]])

In [42]:
m

tensor([[0.9383, 1.8135, 0.1632],
        [1.2421, 1.1895, 1.2812]])

In [ ]:
# NOTE:
# if we want to make permanent changes inplace then
# put _ after a function name
# _ represents that we want to perform inplace operations
# ex: m.relu_()
# m.add_(n)
# etc....

### Copying a Tensor

In [43]:
a = torch.rand(2,3)
a

tensor([[0.3429, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [44]:
b = a

In [45]:
b

tensor([[0.3429, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [ ]:
# the above method of copying ( assignment operator ) has a problem:
# if we make any changes to a
# then that changes reflect on b as well
# example below:

In [46]:
a[0][0] = 0

In [47]:
a

tensor([[0.0000, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [48]:
b

tensor([[0.0000, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [ ]:
# making changes in original
# gets changes in the copy as well
# this is not desirable in some scenarios
# this happens because that's how assignment operator works
# it does not create a new copy in memory but rather points another reference on exisiting tensor

In [49]:
id(a)

136365602225376

In [50]:
id(b)

136365602225376

In [ ]:
# same memory location , it means b is also pointing at same mem location

In [ ]:
# to eliminate this problem we have another function called as
# clone function

In [51]:
b = a.clone()

In [52]:
a

tensor([[0.0000, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [53]:
b

tensor([[0.0000, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [54]:
a[0][0] = 10

In [55]:
a

tensor([[10.0000,  0.5305,  0.7394],
        [ 0.3439,  0.9132,  0.1657]])

In [56]:
b

tensor([[0.0000, 0.5305, 0.7394],
        [0.3439, 0.9132, 0.1657]])

In [55]:
# we see no changes in copy when we make changes in original
# as clone function creates a new tensor in new memory location

In [57]:
id(a)

136365602225376

In [58]:
id(b)

136365405436592

In [ ]:
# diff mem loc means two diff tensors
# therefore making changes in one doesn't affect the other

In [ ]:
# all the operations we performed till now were on cpu
# now let's learn how to perform operations on cpu

## Tensor Operations on GPU

In [60]:
torch.cuda.is_available() # GPU available or not

True

In [61]:
# creating a variable where we store our GPU device

device = torch.device('cuda')

In [62]:
# creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.4470, 0.3305, 0.1066],
        [0.3258, 0.8261, 0.3114]], device='cuda:0')

In [63]:
# moving an existing tensor to GPU
a = torch.rand(2,3) # this tensor is built on CPU
a

tensor([[0.1766, 0.3309, 0.5336],
        [0.0769, 0.5965, 0.7238]])

In [66]:
b = a.to(device) # this tensor is now moved to GPU
b

tensor([[0.1766, 0.3309, 0.5336],
        [0.0769, 0.5965, 0.7238]], device='cuda:0')

In [ ]:
# now all the operations we do on it will be on GPU

In [67]:
b + 5

tensor([[5.1766, 5.3309, 5.5336],
        [5.0769, 5.5965, 5.7238]], device='cuda:0')

In [ ]:
# performance comparison on running tensor on GPU and CPU

In [68]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.rand(size, size) # 10000 x 10000 size matrix
matrix_cpu2 = torch.rand(size, size) # 10000 x 10000 size matrix

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # performing matrix multiplication
cpu_time = time.time() - start_time

print(f"Time taken on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix mul on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time taken on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU TIME / GPU TIME):", cpu_time / gpu_time)

Time taken on CPU: 16.5865 seconds
Time taken on GPU: 0.7188 seconds

Speedup (CPU TIME / GPU TIME): 23.076049989932887


## Reshaping Tensors

In [69]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
# reshape
a.reshape(2,2,2,2)

# note : the product of original shape must be equal to the product of reshape shape.

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [72]:
# flatten - gives one dimensional tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
b = torch.rand(2,3,4)
b

tensor([[[0.0581, 0.8827, 0.0399, 0.7110],
         [0.7565, 0.8324, 0.2100, 0.9287],
         [0.4126, 0.8704, 0.2567, 0.3448]],

        [[0.4683, 0.4925, 0.2591, 0.4894],
         [0.7832, 0.2276, 0.9590, 0.1875],
         [0.1282, 0.8953, 0.8636, 0.9533]]])

In [74]:
# another way of reshaping
# permute
b.permute(2,0,1)

# ex: if we apply b.permute(2,0,1)
#original shape : (2,3,4)
# new shape : (4,2,3)
# this means we want our 2nd shape (2) in original shape which is (4)
# to come to 0th place
# similarly we want our 0th shape (0) in original shape which is (2)
# to come to 1st place
# similarly we want our 1st shape (1) in original shape which is (3)
# to come to 2nd place

tensor([[[0.0581, 0.7565, 0.4126],
         [0.4683, 0.7832, 0.1282]],

        [[0.8827, 0.8324, 0.8704],
         [0.4925, 0.2276, 0.8953]],

        [[0.0399, 0.2100, 0.2567],
         [0.2591, 0.9590, 0.8636]],

        [[0.7110, 0.9287, 0.3448],
         [0.4894, 0.1875, 0.9533]]])

In [75]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# so basically we can reshape our tensor in any permutations

In [76]:
# unsqueeze - at a given position it adds a new dimension
c = torch.rand(226,226,3) # image size
c.unsqueeze(0).shape
#         position

torch.Size([1, 226, 226, 3])

In [77]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [78]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [79]:
c.unsqueeze(3).shape

torch.Size([226, 226, 3, 1])

In [ ]:
# use case of unsqeeze?
# let's say we have a image classification model, generally our dl model
# expects input in batches meaning the model wants (n,226,226,3)
# but we have a single image (226,226,3)
# so we have to first convert it in a single batch
# so to do that we can use unsqueeze operation (very useful in these type of scenarios)

In [80]:
# squeeze - does the opposite of unsqeeze

d = torch.rand(1,20)
d.squeeze(0)
#         position

tensor([0.8115, 0.0442, 0.5497, 0.5919, 0.3348, 0.4257, 0.8327, 0.8687, 0.1672,
        0.8733, 0.0806, 0.9406, 0.8785, 0.1722, 0.6016, 0.2005, 0.0493, 0.3613,
        0.3060, 0.3639])

In [84]:
d.shape

torch.Size([1, 20])

In [82]:
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [90]:
import numpy as np

In [ ]:
# how to move tensors in between numpy and pytorch
# if we want to use pytorch in our numpy , scikitlearn, etc workflow
# and vice versa
# there is a facility where we can convert
# pytorch tensors into numpy arrays
# and numpy arrays into pytorch tensors

In [ ]:
# Converting PyTorch tensor into numpy array

In [85]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [86]:
b = a.numpy() # converts given tensor into numpy array

In [87]:
b

array([1, 2, 3])

In [88]:
type(b)

numpy.ndarray

In [ ]:
# Converting Numpy Array into PyTorch tensor

In [91]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [92]:
torch.from_numpy(c) # converts numpy array into tensor

tensor([1, 2, 3])